### ISSUE TITLE
server.js unable to start in Ubuntu 14.1 64Bit

### ISSUE THREAD

**Issue by kspviswa** [freenetconf/yang-creator#1]
I tried to setup the installation as per the steps in `readme.md`. However I'm hit with following error.

```
root@kspviswa-VirtualBox:/opt/yang-creator# ./server.js 
/opt/yang-creator/node_modules/express/lib/application.js:209
    throw new TypeError('app.use() requires middleware functions');
          ^
TypeError: app.use() requires middleware functions
    at EventEmitter.use (/opt/yang-creator/node_modules/express/lib/application.js:209:11)
    at Object.<anonymous> (/opt/yang-creator/server.js:30:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
root@kspviswa-VirtualBox:/opt/yang-creator# python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
root@kspviswa-VirtualBox:/opt/yang-creator# 
```

**Comment by pkoretic** [comment]
until my pull request is applied you can get fixed version from https://github.com/pkoretic/yang-creator

**Comment by kspviswa** [comment]
I had fixed it myself as follows.

```
File : server.js
Line : 30
app.use(multer({dest:'./uploads/'}).single('import_file'))
```

**Comment by pkoretic** [comment]
even better, latest multer package changed their upload interface so that is where the problem comes
I decided to upgrade rest of the packages while leave this one on tested version

**Comment by kspviswa** [comment]
Does your production code runs on older multer??

**Comment by pkoretic** [comment]
All production code is running on 'older' stable packages which were tested at the time ;) 
Once pull requests get accepted they will get upgraded.

**Comment by kspviswa** [comment]
BTW, Appreciate your initiative on writing yang-creator. I was asked to write a brand-new YANG file ( there was no reference MIB for me). I was seriously looking for YANG creator . 

:+1: 

I also read about future work that is planned. Would there be any opportunity for me to contribute to this software?

**Comment by pkoretic** [comment]
I think there would definitely be opportunity for you to contribute and even appreciated! This was written in short time and there is much to do with little time to spare from my side unfortunately. If you need any help don't hesitate to ask (pkoretic on freenode)

**Comment by kspviswa** [comment]
:+1:

So how's the contribution woks? Do you have any coding guideline, patching guideline etc?
Or you would just follow the Github's pull requests mechanism to review and merge the changes to main repo.

**Comment by pkoretic** [comment]
I think pull request are the best way to go. We will have to wait for @lperkov to chime in since he is actual owner of the repo and project itself.

**Comment by kspviswa** [comment]
@lperkov @pkoretic - Any updates?

**Comment by kspviswa** [comment]
@lperkov @pkoretic  - Any updates?

Is this project still alive?

**Comment by lperkov** [comment]
@kspviswa should be fixed in master now. Thanks to @makkrnic :)
